### ISSUE TITLE
This generator does not show up in a yo search

### ISSUE THREAD

**Issue by stalinkay** [amtrack/generator-md-thesis#1]
Hi,

Please update the generator to show up in a search for thesis. You probably have to add that keyword.

```
? Search npm for generators: thesis
? Sorry, no results matches your search term (Use arrow keys)
❯ Search again 
  Return home
```

**Comment by stalinkay** [comment]
The generator cannot be installed via `npm install -g generator-md-thesis`

Have resorted to this for the time being
`npm install -g git+https://git@github.com/amtrack/generator-md-thesis`

**Comment by stalinkay** [comment]
I'm also getting this stack trace

```
[14:13:55] Using gulpfile /Volumes/Reanimation/thesis/test3/gulpfile.js
[14:13:55] Starting 'build'...
[14:13:55] Starting 'copy-static'...
[14:13:55] Starting 'md2tex'...
events.js:159
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (Error: spawn pandoc ENOENT)
    at Transform.emit (events.js:157:17)
    at Transform.onerror (/Volumes/Reanimation/thesis/test3/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at emitOne (events.js:90:13)
    at Transform.emit (events.js:182:7)
    at Transform.<anonymous> (/Volumes/Reanimation/thesis/test3/node_modules/gulp-pandoc/index.js:38:14)
    at ChildProcess.<anonymous> (/Volumes/Reanimation/thesis/test3/node_modules/pdc/pdc.js:46:12)
    at emitOne (events.js:90:13)
    at ChildProcess.emit (events.js:182:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:202:12)
    at onErrorNT (internal/child_process.js:348:16)
```

**Comment by amtrack** [comment]
@stalinkay Thanks for reporting!
This generator should now show up in the search.

Furthermore, i fixed the error you're describing. Can you please confirm this?

**Comment by stalinkay** [comment]
@amtrack No problem. I haven't tested it but it shows up in search results. I report back if I'm still getting a error.

```
? Search npm for generators: thesis
? Here's what I found. Official generator → ෴
  Install one? (Use arrow keys)
❯ md-thesis Write your thesis in Markdown using gulp.js, Pandoc and TeX Live 
  Search again 
```
